import { CostumeRarity } from "./util"

export const WIKI_HERO_ID_MAP: Record<string, string> = {
    "Adam Warlock":             "adam-warlock",
    "Angela":                   "angela",
    "Black Cat":                "black-cat",
    "Black Panther":            "black-panther",
    "Black Widow":              "black-widow",
    "Blade":                    "blade",
    "Captain America":          "captain-america",
    "Cloak & Dagger":           "cloak-and-dagger",
    "Cyclops":                  "cyclops",
    "Daredevil":                "daredevil",
    "Deadpool":                 "deadpool",
    "Devil Dinosaur":           "devil-dinosaur",
    "Doctor Strange":           "doctor-strange",
    "Elsa Bloodstone":          "elsa-bloodstone",
    "Emma Frost":               "emma-frost",
    "Gambit":                   "gambit",
    "Groot":                    "groot",
    "Hawkeye":                  "hawkeye",
    "Hela":                     "hela",
    "Hulk":                     "bruce-banner",
    "Human Torch":              "human-torch",
    "Invisible Woman":          "invisible-woman",
    "Iron Fist":                "iron-fist",
    "Iron Man":                 "ironman",
    "Jeff the Land Shark":      "jeff-the-land-shark",
    "Jubilee":                  "jubilee",
    "Loki":                     "loki",
    "Luna Snow":                "luna-snow",
    "Magik":                    "magik",
    "Magneto":                  "magneto",
    "Mantis":                   "mantis",
    "Mister Fantastic":         "mister-fantastic",
    "Moon Knight":              "moon-knight",
    "Namor":                    "namor",
    "Peni Parker":              "peni-parker",
    "Phoenix":                  "phoenix",
    "Psylocke":                 "psylocke",
    "Rocket Raccoon":           "rocket-raccoon",
    "Rogue":                    "rogue",
    "Scarlet Witch":            "scarlet-witch",
    "Spider-Man":               "spider-man",
    "Squirrel Girl":            "squirrel-girl",
    "Star-Lord":                "star-lord",
    "Storm":                    "storm",
    "The Punisher":             "the-punisher",
    "The Thing":                "the-thing",
    "Thor":                     "thor",
    "Ultron":                   "ultron",
    "Venom":                    "venom",
    "White Fox":                "white-fox",
    "Winter Soldier":           "winter-soldier",
    "Wolverine":                "wolverine",

    "unknown":                  "unknown"
}

export const WIKI_TYPE_SORT_ID_TO_NAME: Record<string, string> = {
    "000": 'Permanent',
    "010": 'Limited Time',
    "020": 'Lucky Draw',
    "038.02": 'Lucky Draw',
    "030": 'Achievements',
    "031": 'Code Redeemable',
    "032": 'Free Event Reward',
    "038.0": 'Limited Time',
    "038.1": 'Free Event Reward',
    "038.05": 'Free Event Reward',
    "038.08": 'Premium Event Reward',
    "038.2": 'Premium Event Reward',
    "039.1": 'Free Event Reward',
    "039.2": 'Premium Event Reward',
    "040": 'Free Event Reward',
    "050": 'Premium Event Reward',
    "060": 'Free Battle Pass',
    "069": 'Luxury Battle Pass',
    "070": 'Luxury Battle Pass',
    "080": 'Closed Alpha Test',
    "090": 'Closed Beta Test',
    "100": 'Twitch Drop',
    "110": 'PlayStation Exclusive',
    "120": 'Ranked Reward',
    "130": 'Pick-Up Bundle Exclusive',
    "140": 'Disney+ Exclusive',
    "150": 'Esports',

    "default": 'Other'
}

export const COSTUME_RARITIES: Record<string, CostumeRarity> = {
    "2 - Common": "common",
    "3 - Rare": "rare",
    "4 - Epic": "epic",
    "5 - Legendary": "legendary"
}